server:
  port: 9999

spring:
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl